# Generated by Django 2.0 on 2018-03-28 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigerlilly_site', '0003_auto_20180326_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_last', models.CharField(max_length=50)),
                ('alias_first', models.CharField(max_length=50)),
                ('alias_tagline', models.CharField(blank=True, max_length=200, null=True)),
                ('alias_bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_post',
        ),
        migrations.AlterField(
            model_name='issue',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_title',
            field=models.CharField(default='Issue <django.db.models.fields.DecimalField>', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tigerlilly_site.Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tigerlilly_site.Issue'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together={('alias_last', 'alias_first')},
        ),
        migrations.AddField(
            model_name='post',
            name='alias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tigerlilly_site.Alias'),
        ),
    ]
