# Generated by Django 2.0 on 2018-03-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigerlilly_site', '0004_auto_20180327_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
