# Generated by Django 2.0 on 2018-03-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigerlilly_site', '0005_auto_20180327_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
