# Generated by Django 2.0 on 2018-03-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigerlilly_site', '0006_auto_20180328_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ready_to_publish',
            field=models.BooleanField(default=False),
        ),
    ]
