# Generated by Django 2.0 on 2018-03-30 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigerlilly_site', '0007_issue_ready_to_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='ready_to_publish',
            new_name='current_issue',
        ),
    ]
