# Generated by Django 2.0 on 2018-03-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigerlilly_site', '0008_auto_20180329_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='issue_position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('issue', 'issue_position')},
        ),
    ]
